#!/usr/bin/env python3
# -*- coding:utf-8 -*-
from flask import Flask, send_from_directory, make_response, request
import os
app = Flask(__name__)

password = 'tiago'
is_blocked = True

def sendFile(directory, filename):
	print('[+] Shared ', str(directory), '/', str(filename))
	return send_from_directory(directory=directory, filename=filename, as_attachment=True)

def index():
	page = '<!-- FileXSHared By Tiago Danin -->'
	page += '<!-- https://github.com/TiagoDanin/FileXShared  -->'
	page += '''
	<html>
		<head>
			<title>FileXShared</title>
			<style type="text/css">
				.btn {
					margin: 1px;
					font-family: Arial;
					color: #000000;
					font-size: 21px;
					background: #ffffff;
					padding: 10px 5px 10px 5px;
					border: solid #ded5ce 4px;
					align-content: center;
					text-decoration: none;
					width: 100%;
				}

				.btn:hover {
					background: #e67925;
					border: solid #e67925 4px;
					text-decoration: none;
				}
			</style>
		</head>
		<body>
			<form class="form" id="form" name="form" method="post" action="/">

	'''
	get_file = request.form.get('file')
	get_dir = os.getcwd()

	if request.form.get('dir'):
		get_dir = request.form.get('dir')

	if is_blocked:
		if request.cookies.get('password') == str(password):
			print('[+] New login with password')
		elif request.form.get('password') == str(password):
			page += '''
				Password: True
				<button type="submit" class="btn" name="dir" id="id" value="{home}">Go Folder</button></div></br>
			'''.format(home=get_dir)
			page += '''
			</form>
		</body>
	</html>
	'''
			p = make_response(page)
			p.set_cookie('password', str(request.form.get('password')))
			return p
		else:
			page += '''
				Password: <input type='password' class='btn' name='password' id='password' />
			'''
			page += '''
			</form>
		</body>
	</html>
	'''
			p = make_response(page)
			if request.form.get('password'):
				p.set_cookie('password', str(request.form.get('password')))
			return p

	page += '''
				<button type="submit" class="btn" name="dir" id="id" value="{home}">Root Folder</button></div></br>
	'''.format(home=get_dir)
	print(get_dir)

	for path_name, dir_names, file_names in os.walk(str(get_dir_current)):
		for s in dir_names:
			page += '''
				<button type="submit" class="btn" name="dir" id="id" value="{path_name}/{s}">Folder {s}</button></div></br>
	'''.format(s=s, path_name=path_name)
		for s in file_names:
			page += '''
				<button type="submit" class="btn" name="file" id="id" value="{s}">File {s}</button></div></br>
	'''.format(s=s)
		page += '''
			</form>
		</body>
	</html>
	'''
		if get_file:
			for s in file_names:
				if s == get_file:
					print('[+] Seeding ', str(path_name), str(get_file))
					return sendFile(str(path_name), str(get_file))
		else:
			return make_response(page)

app.add_url_rule('/', 'Index', index, methods=['GET'])
app.add_url_rule('/', 'Index', index, methods=['POST'])
if 'TRAVISCL' in os.environ:
	print('TRAVIS-CL OK')
else:
	app.run(host='0.0.0.0', port='8054', debug=False, threaded=True)
